# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWRhYmY1YWQxNGQzMTFmNzYxYzliMzU5YzdkZmQ3OTVkYzgxMGQ5NTc3ZjdjZDdmYThkZjBlYmE0YWU5ZWUwMzg3ODNmYzI5YjdjNjUwNWQ1NGYxZGY2ZGMzODYyOWRkMzg0ODFkODNmNDc2MjNlYTYwMDlkOThkNTkyZGRkMmI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
